[package]
name = "portdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
uuid = { version = "1.8.0", features = ["v4", "serde"] }

[dev-dependencies]
rstest = "0.21.0"

[workspace]
members = ["viewer/wasm"]
